### PR TITLE
UDP Join Implemented

### PR DESCRIPTION
**Pull request by scartill**

### CODE REVIEW

**Comment by starsky35** [comment]
@scartill, thanks very much for your branch !
I started to test it but it is very hard for me to check downlink message reception because I faced constant GUI crash after sometimes when scrolling the output console log  (I log a new issue for it).
I already noticed this issue in past version but it becomes worst  because of the increase of logs due to PULL_DATA implementation.

However one remark from what I have seen so far, there is no button to stop/disconnect the forwarder once connected.

**Comment by scartill** [comment]
@starsky35 Thanks for testing, that really helps!
* as for crash - never saw this, will try to reproduce according to you issue
* as for disconnect - yeah, I'm aware of it. Requires some extra refactoring, will do a.s.a.p.

**Comment by Gillani0** [comment]
@starsky35  Thanks for the quick response. From my initial tests, I'm unable to receive the join request on UDP (even TCP dump won't give me anything). Furthermore, why it needs a MQTT server to be started to use UDP?

**Comment by scartill** [comment]
@Gillani0 MQTT shouldn't be started. On the contrary, MQTT and UDP modes are mutially exculusive. Please use Forwarder/Connect button before using UDP Join

**Comment by starsky35** [comment]
After some more tests (even if GUI crash make me crazy !), seems OTAA activation and Downlink frame reception in UDP works most of the time except when I got error on join resp decryption ("downlink error : MACPayload must be of type*MACPayload")

pullresp_error

**Comment by Gillani0** [comment]
Rebuilding the project made it work. However, I had the similar issue of parsing the MACPayload.
I've not looked into the code but are you following the parsing model for [semtech UDP forwarder](https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT)?

**Comment by scartill** [comment]
@starsky35  "downlink error" issue is associated with re-join, because frame and join processing is differentiated base on profile and current status. See https://github.com/iegomez/lds/blob/master/lds/lds.go#L369.

I would kindly ask @iegomez to clarify whether there is more correct and still concise way to tell join response from downlink frame?

**Comment by iegomez** [comment]
I'll be totally honest: I haven't touched these things in a long time as I no longer do LoRaWAN related work nor do I have infrastructure for it, and this particular week we are wrapping up a project at work so I have very little time to check other stuff. That is, sorry, guys, I won't be of much help.

**Comment by scartill** [comment]
Created distinct #19 issue, merging this

**Pull request merged**
